print('BRIDGEKEEPER: Stop.')
print('Who would cross the Bridge of Death must answer me these questions three.')
print('BRIDGEKEEPER: What is your name?')
name = input()
print('BRIDGEKEEPER: What is your quest?')
quest = input()
print('BRIDGEKEEPER: What is your favorite color?')
colour = input()
print('----------')
print('Traveler info:')
print('Your name is', name)
print('Your quest is', quest)
print('Your favorite color is', colour)
print('----------')
print('BRIDGEKEEPER: Right. Off you go')
